language: generic

matrix:
  include:
    - os: linux
      env: DOCKERIMAGE=linux-anvil:gcc-5

    - os: linux
      env: DOCKERIMAGE=linux-anvil
      
    - os: linux
      env: DOCKERIMAGE=linux-anvil-ppc64le

env:
  global:
    secure: TQkj0g+2b3yHi3uVPii7OWPrJ6w/FpBmm4Fv0C0NbWU7P6xOBDawAX+FnwxsvlGUVh5sy3f2HjSfOUGVAOgSI1sdnQ2EWJSpabK6s5s/X7CPj/7v/CPjIodAoWkfM7qDnTHBhZmOGMSZOLCx57fDbiPcwS4ltgnz02C4sENJb5MrK6a6zaDeMyaEZtMgBWPnRMh2GsHRtkONCOttjYiLj0NIBrjZsxCxx3nT0SzJWfh+6gLyGVjZoTtex1v6zroYgrfmgvGZFPWNhj75bzdltkctpn1hIdZ6B7R72hBMdWUIeW1vL6Mk4to09czNQBj37l9f4XJE6B27mcP2NXX92/jyxVPJl4BeUv0xU9d3CZgwiHUJUfSMVZDPRWa3YAMTwpOknOk7/6BGnwYhk64p47XeWEGOvicL6xJaW2VyRB1zIurIKiu5fC0mJ1UdWsU1sIEM+cwO5pTywZnPqVq7ta2ORAsw19hdpCO3RAtzFE31SXkhhEJyrr25zyv74QZ9b/THUPwHrGumicFbB/mm1Gs2fEsSTnCvgatIRze2y5egXRhyxF37y3c2ghe3MQpXvjBlVO6tqGFlhYAjQkSTd/fMyrodxyljeEqvh3kATO2Q//LrjXLdwL0PY1ymbxGixnfFnC+Xz8Wube22+LdSjqU8T61H4IsIUaSmLg/bP7Y=

before_install:
    - docker info
    - |
      if [ "$(uname -m)" = "x86_64" ]; then
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
      fi
      export QEMU_STATIC_VERSION=v3.1.0-2
      wget https://github.com/multiarch/qemu-user-static/releases/download/${QEMU_STATIC_VERSION}/qemu-ppc64le-static
      wget https://github.com/multiarch/qemu-user-static/releases/download/${QEMU_STATIC_VERSION}/qemu-aarch64-static
      chmod +x qemu-ppc64le-static
      chmod +x qemu-aarch64-static

install:
    - |
      $DOCKERIMAGETAG=$(echo $DOCKERIMAGE | cut -d ':' -f2)
      if [[ ! -z "$DOCKERIMAGETAG" ]]
      then
        mkdir -p $DOCKERIMAGE
        sed "s|@BASE_IMAGE@|practicalci/${DOCKERIMAGE/:$DOCKERIMAGETAG/}|" $DOCKERIMAGETAG/Dockerfile.in > $DOCKERIMAGE/Dockerfile
      fi
    - docker build -t practicalci/$DOCKERIMAGE -f $DOCKERIMAGE/Dockerfile --no-cache .

script:
    - |
      if [[ ! $DOCKERIMAGE =~ "jnlp-slave" ]]
      then
        ./.circleci/run_docker_build.sh
      fi

deploy:
  provider: script
  script: docker login -u practicalcibot -p $DH_PASSWORD && docker push practicalci/$DOCKERIMAGE
