language: generic

matrix:
  include:
    - os: linux
      env: DOCKERIMAGE=linux-anvil
      
    - os: linux
      env: DOCKERIMAGE=linux-anvil:gcc-5

    - os: linux
      env: DOCKERIMAGE=linux-anvil-ppc64le

before_install:
    - docker info
    - |
      if [ "$(uname -m)" = "x86_64" ]; then
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
      fi
      export QEMU_STATIC_VERSION=v3.1.0-2
      wget https://github.com/multiarch/qemu-user-static/releases/download/${QEMU_STATIC_VERSION}/qemu-ppc64le-static
      wget https://github.com/multiarch/qemu-user-static/releases/download/${QEMU_STATIC_VERSION}/qemu-aarch64-static
      chmod +x qemu-ppc64le-static
      chmod +x qemu-aarch64-static

install:
    - |
      DOCKERBASEIMAGE=$(echo $DOCKERIMAGE | cut -d ':' -sf1)
      DOCKERIMAGETAG=$(echo $DOCKERIMAGE | cut -d ':' -sf2)
      if [ ! -z "$DOCKERIMAGETAG" ]
      then
          mkdir -p $DOCKERIMAGE
          sed "s|@BASE_IMAGE@|practicalci/${DOCKERBASEIMAGE}|" $DOCKERIMAGETAG/Dockerfile.in > $DOCKERIMAGE/Dockerfile
      fi
    - docker build -t practicalci/$DOCKERIMAGE -f $DOCKERIMAGE/Dockerfile --no-cache .

script:
    - |
      if [[ ! $DOCKERIMAGE =~ "jnlp-slave" ]]
      then
        ./.circleci/run_docker_build.sh
      fi

deploy:
  provider: script
  script: echo $DH_PASSWORD | docker login -u practicalcibot --password-stdin  && docker push practicalci/$DOCKERIMAGE
