FROM @BASE_IMAGE@

# this is required for dockcross script.
ARG IMAGE=practicalci/linux-anvil
ARG VERSION=gcc-7
ENV DEFAULT_DOCKCROSS_IMAGE ${IMAGE}:${VERSION}

RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
                   g++ \
                   gcc \
                   g++-7 \
                   gcc-7 \
                   clang-tools-6.0 \
                   clang-tidy-6.0 \
                   clang-format-6.0 \
                   valgrind \
                   iwyu && \
    apt-get clean -y && \
    apt-get autoremove --purge -y && \
    rm -rf /var/lib/apt/lists/*
