FROM @BASE_IMAGE@

RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
                   g++-7 \
                   gcc-7 \
                   clang-tidy-6.0 \
                   clang-format-6.0 && \
    apt-get clean -y && \
    apt-get autoremove --purge -y && \
    rm -rf /var/lib/apt/lists/*
